language: c
os: osx
osx_image: xcode9.3

before_install:
 - export NUM_CPUS=$(sysctl -n hw.ncpu)

install:
 - brew install cctools nasm
 - ln -s /usr/local/opt/cctools/bin/mtoc /usr/local/bin/mtoc
 - git clone https://github.com/tianocore/edk2 ../edk2 --depth 1
 - make -C ../edk2/BaseTools -s -j $NUM_CPUS

before_script:
 - cd ../edk2
 - source edksetup.sh
 - export PACKAGES_PATH="$(pwd)/.."
 - export TOOLCHAIN="XCODE5"
 - cd $TRAVIS_BUILD_DIR
 - ./gen-version.sh $TOOLCHAIN

script:
 - build -p Clover/Clover.dsc -a IA32 -b RELEASE -t $TOOLCHAIN -n $NUM_CPUS -s
 - build -p Clover/Clover.dsc -a X64 -b RELEASE -t $TOOLCHAIN -n $NUM_CPUS -s
